### ISSUE TITLE
Range tools fail when viewing JLS v2 files

### ISSUE THREAD

**Issue by mliberty1** [jetperch/pyjoulescope_ui#131]
Version: 0.9.9 (alpha)
Platforms: Windows tests, but likely all

**Description**

If you load a JLS v2 file, add dual markers, and then try to export or run any of the analysis tools, you get the following error:

```
ERROR:2021-07-14 12:54:15,261:main.py:1772:joulescope_ui.main:range tool run
Traceback (most recent call last):
  File "C:\repos\Jetperch\pyjoulescope_ui\joulescope_ui\main.py", line 1770, in _cmd_range_tool_run
    invoke.run(self._data_view, s, x_start, x_stop)
  File "C:\repos\Jetperch\pyjoulescope_ui\joulescope_ui\range_tool.py", line 171, in run
    s1 = max(view.time_to_sample_id(t1), 0)  # negative sample_ids not allowed
AttributeError: 'RecordingView' object has no attribute 'time_to_sample_id'
```

**Expected behavior**
The dual-marker analysis and export features should work on JLS v2 files.

**Comment by mliberty1** [comment]
Fixed for all the analysis tools in f61f4d0c0cebb420d1b549553028eed5fb77635c.  However, `export` still fails since it tries to write to a JLS v1 file.  Currently, JLS v2 files do not have all the needed info to support JLS v1 writes.
