### ISSUE TITLE
UI crashing on open if viewing JLS file that was deleted

### ISSUE THREAD

**Issue by mliberty1** [jetperch/pyjoulescope_ui#264]
### Joulescope model

JS220

### UI version

1.0.58

### What OS are you seeing the problem on?

Windows 11

### What happened?

When I attempt to open the UI, it crashes.  Inspecting the log, it shows:

```
ERROR:2024-04-30 08:45:06,204:pubsub.py:1141:joulescope_ui.pubsub:register(unique_id=JlsSource:00000003) callback failed
Traceback (most recent call last):
  File "C:\PROGRA~1\JOULES~1\joulescope_ui\pubsub.py", line 1138, in register
  File "C:\PROGRA~1\JOULES~1\joulescope_ui\pubsub.py", line 1334, in _register_invoke_callback
  File "C:\PROGRA~1\JOULES~1\joulescope_ui\pubsub.py", line 1323, in <lambda>
  File "C:\PROGRA~1\JOULES~1\joulescope_ui\jls_source.py", line 126, in on_pubsub_register
  File "C:\PROGRA~1\JOULES~1\joulescope_ui\jls_source.py", line 42, in _jls_version_detect
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mliberty\\Documents\\joulescope\\20240423_164605.jls'
INFO:2024-04-30 08:45:06,205:app.py:235:joulescope_ui.app:Capability signal_buffer.source: ['JsdrvStreamBuffer:001', 'JlsSource:00000003']
INFO:2024-04-30 08:45:06,205:pubsub.py:1143:joulescope_ui.pubsub:register(unique_id=JlsSource:00000003) done ABORT
INFO:2024-04-30 08:45:06,205:pubsub.py:1374:joulescope_ui.pubsub:unregister(unique_id=JlsSource:00000003, obj=<joulescope_ui.jls_source.JlsSource object at 0x000001AC52FE32D0>) start
INFO:2024-04-30 08:45:06,205:app.py:235:joulescope_ui.app:Capability signal_buffer.source: ['JsdrvStreamBuffer:001']
INFO:2024-04-30 08:45:06,205:jls_source.py:171:joulescope_ui.jls_source:close C:\Users\mliberty\Documents\joulescope\20240423_164605.jls
INFO:2024-04-30 08:45:06,205:jls_source.py:178:joulescope_ui.jls_source:close done C:\Users\mliberty\Documents\joulescope\20240423_164605.jls
INFO:2024-04-30 08:45:06,205:main.py:820:joulescope_ui.main:finalize: config save
INFO:2024-04-30 08:45:06,205:pubsub.py:1510:joulescope_ui.pubsub:save 'C:\\Users\\mliberty\\AppData\\Local\\joulescope\\config\\joulescope_ui_config.json'
INFO:2024-04-30 08:45:06,205:js220_usb.c:432:jsdrv:publish to dev ? nul    
INFO:2024-04-30 08:45:06,205:js220_usb.c:432:jsdrv:publish to dev c/!ping u32    2
INFO:2024-04-30 08:45:06,208:js220_usb.c:658:jsdrv:open complete
INFO:2024-04-30 08:45:06,211:js220_usb.c:432:jsdrv:publish to dev s/stats/ctrl  u8.R  1
INFO:2024-04-30 08:45:06,215:js220.py:780:joulescope_ui.devices.jsdrv.device.u.js220.002122:open JS220-002122 done
INFO:2024-04-30 08:45:06,215:js220.py:734:joulescope_ui.devices.jsdrv.device.u.js220.002122:thread open complete
INFO:2024-04-30 08:45:06,215:release.py:188:pyjoulescope_driver.release:release_get found img_stable.img using pkgutil.get_data
ERROR:2024-04-30 08:45:06,216:main.py:947:joulescope_ui.main:UI crash
Traceback (most recent call last):
  File "C:\PROGRA~1\JOULES~1\joulescope_ui\main.py", line 927, in run
  File "C:\PROGRA~1\JOULES~1\joulescope_ui\main.py", line 311, in __init__
  File "C:\PROGRA~1\JOULES~1\joulescope_ui\pubsub_proxy.py", line 86, in register
  File "C:\PROGRA~1\JOULES~1\joulescope_ui\pubsub.py", line 1146, in register
RuntimeError: register(unique_id=JlsSource:00000003) aborted
```

I had deleted the JLS file that it was trying to open.

### What was expected?

The UI should not crash.  It should open without displaying the JLS file.

### How to reproduce?

1. Open the Joulescope UI
2. Switch to View → File,  and select File → Open, and open a JLS file
3. Close the Joulescope UI
4. Delete the selected JLS file
5. Start the Joulescope UI, which then crashes

**Comment by mliberty1** [comment]
Available in 1.1.7
