### ISSUE TITLE
Crash with Arduino Nano 33 BLE target

### ISSUE THREAD

**Issue by mliberty1** [jetperch/pyjoulescope_ui#30]
Joulescope UI 0.6.8
Win10 x64

After upgrading to 0.6.8 from 0.6.3, frequent (every few minutes) Joulescope UI crashes occur.  When uploading programs to an Arduino Nano 33 BLE attached as the load, the Joulescope UI crashes frequently.  See [forum](https://forum.joulescope.com/t/frequent-crashes-in-0-6-8) for full description and log files.

After inspecting the logs, the common error is:

    Windows fatal exception: access violation

but the error occurs in different locations.

[Differences](https://github.com/jetperch/pyjoulescope/compare/6aeda80e3433e70184c7d806f5ea73822486b451...v0.6.8) between pyjoulescope 0.6.3 and 0.6.8.

### Crash locations in the provided logs

File "site-packages\joulescope\driver.py", line 342 in open
    joulescope_20191114_204349_6204.log - immediately at start
    joulescope_20191114_203423_9856.log - immediately at start
    joulescope_20191114_201445_15440.log - on_statusUpdateTimer timeout
    joulescope_20191114_193211_11196.log - on_statusUpdateTimer timeout
    joulescope_20191114_192145_9784.log - on_statusUpdateTimer timeout

File "site-packages\joulescope\driver.py", line 343 in open
    joulescope_20191114_200553_21728.log - on_statusUpdateTimer timeout

File "site-packages\joulescope\driver.py", line 262 in parameters (deepcopy)
    joulescope_20191114_205414_10172.log - immediately at start
    joulescope_20191114_191138_11904.log - on_statusUpdateTimer timeout, then on open
    joulescope_20191114_211037_17152.log - immediately at start

File "joulescope_ui\main.py", line 421 in on_statusUpdateTimer (formatTime in logging)
    joulescope_20191114_202630_21940.log - immediately at start
    joulescope_20191114_201716_26564.log - on_statusUpdateTimer timeout

File "site-packages\joulescope\usb\device_thread.py", line 93 in _cmd_process_all (formatTime in logging)
    joulescope_20191114_195217_14164.log - after device thread hung

The joulescope_20191114_201716_26564.log is an example of on_statusUpdateTimer then crash 
```
INFO:2019-11-14 21:25:50,739:driver.py:1159:joulescope.driver:scan_for_changes 1 devices: 0 added, 0 removed
INFO:2019-11-14 21:25:50,739:main.py:965:joulescope_ui.main:current device = Joulescope:000491, False
INFO:2019-11-14 21:25:50,739:main.py:971:joulescope_ui.main:_device_scan done
INFO:2019-11-14 21:25:50,987:main.py:495:joulescope_ui.main:Device notify
INFO:2019-11-14 21:25:50,987:main.py:951:joulescope_ui.main:_device_scan start
INFO:2019-11-14 21:25:50,988:driver.py:1159:joulescope.driver:scan_for_changes 1 devices: 0 added, 0 removed
INFO:2019-11-14 21:25:50,989:main.py:965:joulescope_ui.main:current device = Joulescope:000491, False
INFO:2019-11-14 21:25:50,989:main.py:971:joulescope_ui.main:_device_scan done
INFO:2019-11-14 21:25:51,087:main.py:495:joulescope_ui.main:Device notify
INFO:2019-11-14 21:25:51,087:main.py:951:joulescope_ui.main:_device_scan start
INFO:2019-11-14 21:25:51,088:driver.py:1159:joulescope.driver:scan_for_changes 1 devices: 0 added, 0 removed
INFO:2019-11-14 21:25:51,088:main.py:965:joulescope_ui.main:current device = Joulescope:000491, False
INFO:2019-11-14 21:25:51,088:main.py:971:joulescope_ui.main:_device_scan done
ERROR:2019-11-14 21:26:15,764:device_thread.py:151:joulescope.usb.device_thread:device thread hung: control_transfer_in - FORCE CLOSE
INFO:2019-11-14 21:26:15,764:device.py:659:joulescope.usb.winusb.device:WinUsbDevice.close
INFO:2019-11-14 21:26:15,764:device.py:385:joulescope.usb.winusb.device:endpoint stop
INFO:2019-11-14 21:26:15,765:driver.py:590:joulescope.driver:streaming done(0, )
INFO:2019-11-14 21:26:17,764:device_thread.py:93:joulescope.usb.device_thread:DeviceThread._cmd_process_all close
INFO:2019-11-14 21:26:17,764:device_thread.py:123:joulescope.usb.device_thread:DeviceThread.run flush
INFO:2019-11-14 21:26:17,764:device_thread.py:125:joulescope.usb.device_thread:DeviceThread.run done
ERROR:2019-11-14 21:26:17,764:main.py:421:joulescope_ui.main:statusUpdateTimer failed - assume device error
Traceback (most recent call last):
  File "joulescope_ui\main.py", line 407, in on_statusUpdateTimer
  File "site-packages\joulescope\driver.py", line 819, in status
  File "site-packages\joulescope\driver.py", line 761, in _status
  File "site-packages\joulescope\usb\device_thread.py", line 197, in control_transfer_in
  File "site-packages\joulescope\usb\device_thread.py", line 159, in _post_block
OSError
INFO:2019-11-14 21:26:17,765:main.py:873:joulescope_ui.main:_device_recover: start
INFO:2019-11-14 21:26:17,765:main.py:902:joulescope_ui.main:_device_change remove
INFO:2019-11-14 21:26:17,765:main.py:833:joulescope_ui.main:device_close Joulescope:000491
INFO:2019-11-14 21:26:17,766:view.py:431:joulescope.view:close
INFO:2019-11-14 21:26:17,766:view.py:183:joulescope.view:View.run done
INFO:2019-11-14 21:26:17,766:driver.py:661:joulescope.driver:stop : streaming=True
WARNING:2019-11-14 21:26:17,766:device_thread.py:139:joulescope.usb.device_thread:response queue not empty
INFO:2019-11-14 21:26:17,766:device_thread.py:130:joulescope.usb.device_thread:DeviceThread.post(read_stream_stop) when thread not running
ERROR:2019-11-14 21:26:17,766:driver.py:461:joulescope.driver:USB stop failed
Traceback (most recent call last):
  File "joulescope_ui\main.py", line 407, in on_statusUpdateTimer
  File "site-packages\joulescope\driver.py", line 819, in status
  File "site-packages\joulescope\driver.py", line 761, in _status
  File "site-packages\joulescope\usb\device_thread.py", line 197, in control_transfer_in
  File "site-packages\joulescope\usb\device_thread.py", line 159, in _post_block
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\joulescope\driver.py", line 459, in close
  File "site-packages\joulescope\driver.py", line 663, in stop
  File "site-packages\joulescope\usb\device_thread.py", line 203, in read_stream_stop
  File "site-packages\joulescope\usb\device_thread.py", line 146, in _post_block
OSError: DeviceThread not running
INFO:2019-11-14 21:26:17,770:main.py:1191:joulescope_ui.main:_device_stream(False)
INFO:2019-11-14 21:26:17,770:main.py:1183:joulescope_ui.main:_device_stream_stop when no device
INFO:2019-11-14 21:26:17,770:main.py:590:joulescope_ui.main:_accumulators_zero_last
INFO:2019-11-14 21:26:17,770:main.py:878:joulescope_ui.main:_device_recover: done
INFO:2019-11-14 21:26:17,773:scrollbar.py:181:joulescope_ui.oscilloscope.scrollbar:set_display_mode(buffer)
INFO:2019-11-14 21:26:17,779:main.py:951:joulescope_ui.main:_device_scan start
INFO:2019-11-14 21:26:17,780:driver.py:1159:joulescope.driver:scan_for_changes 1 devices: 1 added, 0 removed
INFO:2019-11-14 21:26:17,780:main.py:891:joulescope_ui.main:_device_change add Joulescope:000491
INFO:2019-11-14 21:26:17,780:main.py:965:joulescope_ui.main:current device = disable, True
INFO:2019-11-14 21:26:17,780:main.py:967:joulescope_ui.main:device_scan activate first device Joulescope:000491
INFO:2019-11-14 21:26:17,780:main.py:833:joulescope_ui.main:device_close disable
INFO:2019-11-14 21:26:17,780:main.py:590:joulescope_ui.main:_accumulators_zero_last
INFO:2019-11-14 21:26:17,781:main.py:670:joulescope_ui.main:device_open Joulescope:000491
INFO:2019-11-14 21:26:17,781:main.py:590:joulescope_ui.main:_accumulators_zero_last
INFO:2019-11-14 21:26:17,781:device_thread.py:174:joulescope.usb.device_thread:open
INFO:2019-11-14 21:26:17,781:device_thread.py:116:joulescope.usb.device_thread:DeviceThread.run start
INFO:2019-11-14 21:26:17,782:device.py:659:joulescope.usb.winusb.device:WinUsbDevice.close
INFO:2019-11-14 21:26:17,782:device.py:620:joulescope.usb.winusb.device:WinUsbDevice.open
INFO:2019-11-14 21:26:17,782:device.py:649:joulescope.usb.winusb.device:is_high_speed = True
INFO:2019-11-14 21:26:17,782:device.py:650:joulescope.usb.winusb.device:interface_settings = InterfaceDescriptor(
    length=9,
    descriptor_type=4,
    interface_number=0,
    alternate_setting=0,
    num_endpoints=2,
    interface_class=255,
    interface_sub_class=0,
    interface_protocol=0,
    interface=0)
Windows fatal exception: access violation

Thread 0x00000d90 (most recent call first):
  File "site-packages\joulescope\usb\winusb\device.py", line 784 in process
  File "site-packages\joulescope\usb\device_thread.py", line 119 in run
  File "threading.py", line 865 in run
  File "threading.py", line 917 in _bootstrap_inner
  File "threading.py", line 885 in _bootstrap

Thread 0x00003940 (most recent call first):
  File "site-packages\joulescope\usb\winusb\win32_device_notify.py", line 119 in _run_window
  File "threading.py", line 865 in run
  File "threading.py", line 917 in _bootstrap_inner
  File "threading.py", line 885 in _bootstrap

Current thread 0x000057f4 (most recent call first):
  File "site-packages\joulescope\driver.py", line 342 in open
  File "joulescope_ui\main.py", line 677 in _device_open
  File "joulescope_ui\main.py", line 895 in <lambda>
  File "joulescope_ui\main.py", line 968 in _device_scan
  File "joulescope_ui\main.py", line 975 in on_deviceScan
  File "joulescope_ui\main.py", line 1551 in run
  File "joulescope_ui\command.py", line 49 in on_cmd
  File "joulescope_ui\__main__.py", line 28 in <module>
```

**Comment by mliberty1** [comment]
Since we have no further reports and I could not identify the cause, I am going to close this issue.  
FOR FUTURE REFERENCE: in case we get similar reports.
