### ISSUE TITLE
"General/data_path" needs better error handling

### ISSUE THREAD

**Issue by mliberty1** [jetperch/pyjoulescope_ui#32]
Platform: Win 10 x64
Joulescope UI version: 0.7.0

A customer reported an issue with 0.6.8 where cfg["General"]["data_path"] was null in the JSON file:

```
{
  "General": {
    "data_path": null,
    "update_check": true,
    "log_level": "INFO"
  },
...
```
which caused the application not to start with the error:
Failed to execute script __main__

The actual issue was accessing the variable which failed path validation.

How does 0.7.0 work?  0.7.0 has many changes to preferences, but I tested and found weaknesses.  We should improve the Joulescope UI error checking and error handling for bad path values.

The configuration file is stored to:  "c:\User\{username|\AppData\local\joulescope\config\joulescope_config.json "
And the corresponding setting is:
"General/data_path": "C:\\Users\\mliberty\\Documents\\joulescope",

If I set this to null and then start, the application still runs.  However, selecting File -> Open does not work:
```
Traceback (most recent call last):
  File "D:\repos\Jetperch\pyjoulescope_ui\joulescope_ui\main.py", line 983, in on_recording_open
    self, 'Open Joulescope Recording', self._path, 'Joulescope Data (*.jls)')
  File "D:\repos\Jetperch\pyjoulescope_ui\joulescope_ui\main.py", line 354, in _path
    if not os.path.isdir(path):
TypeError: _isdir: path should be string, bytes or os.PathLike, not NoneType
```

If I close the application, set "General/data_path" to "" (empty string), run, then select File -> Open, it still doesn't work, and I get:
```
Traceback (most recent call last):
  File "D:\repos\Jetperch\pyjoulescope_ui\joulescope_ui\main.py", line 983, in on_recording_open
    self, 'Open Joulescope Recording', self._path, 'Joulescope Data (*.jls)')
  File "D:\repos\Jetperch\pyjoulescope_ui\joulescope_ui\main.py", line 355, in _path
    os.makedirs(path, exist_ok=True)
  File "D:\venv\joulescope\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
```

**Comment by mliberty1** [comment]
The Preferences dialog should also handle more robust data path selection.  What should happen if the user enters an empty path?  Perhaps the Preferences dialog should use the last known good path.  Keeping a most recently used history of selected paths would also be useful to allow the user to change quickly.  If the user saves a recording to a different path, should we update the data path automatically?
